version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - modernize
    - nilerr
    - nilnesserr
    - nilnil
    - nolintlint
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign

  settings:
    govet:
      enable:
        - shadow

formatters:
  enable:
    - gofmt
    - goimports
